### ISSUE TITLE
Enhancement: Separate configurations for package and database

### ISSUE THREAD

**Issue by magicalbanana** [rnubel/pgmgr#20]
Currently `pgmgr` looks for a `.pgmgr.json` file to set the package and database configuration.
Although we are able to override the default search path via `PGMGR_CONFIG_FILE` I propose that
the `.pgmgr.json` configuration will only have configuration attributes specific to the package commands.

So instead of this configuration (which is db config related):

```json
{
  "host": "localhost",
  "port": 5432,
  "username": "test",
  "password": "test",
  "database": "testdb",
  "migration-table": "public.schema_migrations",
  "migration-folder": "db/migrate",
  "dump-file": "db/dump.sql",
  "column-type": "integer",
  "format": "unix",
  "seed-tables": [ "foos", "bars" ]
}
```

It would be better if we have this file configure where the database configuration resides and toggle the different configurations via env vars that has a default to development. 

```json
{
  "dbconfig-folder": "config/db.conf.json",
  "migration-folder": "db/migrate",
  "dump-file": "db/dump.sql"
}
```

This would still work well with the current configuration that allows overrides with the environmental variables.

**Comment by rnubel** [comment]
I recognize what you're getting at -- that the config file mixes repo-level, unlikely-to-change config values with environment-dependent, likely to change config values -- but introducing a separate config file seems a bit too complicated. I would suggest instead that you put your global config into your `.pgmgr.json`, and use environment variables to change any environment-dependent values.

**Comment by magicalbanana** [comment]
Yeah, actually after working with `go` for a couple weeks now I changed my mind on this seeing that there are packages to handle different envs.

But we can introduce it though. Keeping what you already have and extending the config by adding environments or something. But I'll get back to that when I get the chance, we can close this for now. :)

**Comment by rnubel** [comment]
Sounds good!
