### ISSUE TITLE
How to connect via SSL

### ISSUE THREAD

**Issue by abhinavzspace** [rnubel/pgmgr#26]
We are using this tool heavily in our project in development.

We need to connect to heroku-postgres. It requires SSL. I checked that sslmode=require functionality is a TODO. But for now, what could be the way to connect, until this is implemented?

Thanks!

**Comment by rnubel** [comment]
Good point. I don't think there's any real reason for not having this functionality. I'll work on adding it today, unless you (or someone else) wants to try their hand at a PR.

**Comment by rnubel** [comment]
@abhinavzspace pgmgr now supports the `sslmode` configuration parameter (see https://github.com/rnubel/pgmgr/commit/f1165825ff12025a77969e64da296ff299cf7701 for more info). Please let me know if it works correctly for you!

**Comment by abhinavzspace** [comment]
@rnubel I will check and let you know. And really sorry that I could not comment earlier.

**Comment by abhinavzspace** [comment]
It is working as expected, as far as I can check.
Thanks!
