### ISSUE TITLE
Usable as a library/package

### ISSUE THREAD

**Issue by magicalbanana** [rnubel/pgmgr#28]
Right now (correct me if I am wrong) but it's usage is tied to the CLI right?
What're your thoughts on allowing the package to be used in a code?

**Comment by rnubel** [comment]
The `pgmgr` package can definitely be used on its own within another app -- if you look at `main.go`, it's effectively doing just that -- although since it writes to stdout by default and generally works entirely off of the `Config` object, it's probably pretty awkward to do so. I'd have to see some use cases.

**Comment by magicalbanana** [comment]
But looking at how the config is loaded it's expecting a context through the `cli` package.
The use case would be when you want to make a specific integration tests that does a lot of what you would normally use pgmgr for like create db, run migrations, drop it, etc.

**Comment by skinnyjames** [comment]
Hi all, I think I might have a use case - at least a question.

I'm working on an app to be distributed, which has to connect to the database to perform tasks as well as run versioned migrations.   It seems I'll need to share the pgmgr config with the app itself, which currently may dynamically create it from a form. Trying to figure out the best way to integrate the app and pgmgr.  Any ideas?

**Comment by rnubel** [comment]
@skinnyjames if you use the standard PG environment variables to configure pgmgr, those should also be usable for your application. Let me know if you run into any issues doing so. (for example, I know the warning about `.pgmgr.json not found` gets a little annoying, so maybe we should pull that out if the env variables exist.)
