### ISSUE TITLE
Environment variable duplications

### ISSUE THREAD

**Issue by tbruyelle** [rnubel/pgmgr#3]
Is there a reason why you duplicate the standards postgres environment variables into the `PGMGR_*` ones ?

If they're no specific reason, I think you should reuse the ones from postgres, it would be more convenient for the user.

**Comment by rnubel** [comment]
My initial reasoning was to decouple the environment we're targeting from the environment we're running on; for example, suppose you have those environment variables set locally but are using pgmgr to migrate a remote database -- you'd expect the configuration to be read only from the configuration file, and not default to local environment settings.

However, that scenario is definitely an edge case. I think your scenario (expecting pgmgr to default to the standard PG* variables) is more plausible. What if we support both sets of variables, but prefer the PGMGR* values if present?

**Comment by tbruyelle** [comment]
I think that's a good idea :+1:

**Comment by rnubel** [comment]
@tbruyelle This should be fixed by #5. Let me know if it doesn't work as expected, and thanks for opening this issue!
