### ISSUE TITLE
Password in the DSN

### ISSUE THREAD

**Issue by skinnyjames** [rnubel/pgmgr#32]
It doesn't look like the password for the database gets parsed by `func (config *Config) overrideFromURL()`
whereas the documentation seems like it would.  Is there a reason for that? 
I can make a PR if not, otherwise I might be missing your intention?

**Comment by rnubel** [comment]
Hm, I don't think there's any specific reason other than it not being in my initial use case for supporting DSNs. I'll be happy to merge a PR if you make one.

**Comment by skinnyjames** [comment]
Made a pull request, not exactly sure why it's failing CI though.  :\

**Comment by skinnyjames** [comment]
#33
