### ISSUE TITLE
error during migration: pq: role "root" does not exist

### ISSUE THREAD

**Issue by skinnyjames** [rnubel/pgmgr#35]
Was using pgmgr yesterday with the connection string in the environment, now it doesn't seem to recognize the user in a CI environment.  I'll double check to see if I'm doing anything different, but I do not think I am.

     PGMGR_URL='postgres://postgres@database:5432/postgres?sslmode=disable' pgmgr db migrate
     Error during migration: pq: role "root" does not exist`

**Comment by rnubel** [comment]
Can you run `pgmgr config` and check the output to see if your config is being loaded correctly? Locally for me, `pgmgr` is able to extract my username from PGMGR_URL without an issue.

**Comment by skinnyjames** [comment]
Strange, the config looks great.  I'm running it against a docker service in CI, so maybe I'm goofing up there.  
    
    PGMGR_URL='postgres://postgres@database:5432/postgres?sslmode=disable' pgmgr config
    &{Username:postgres Password: Database:postgres Host:database Port:5432 
    URL:postgres://postgres@database:5432/postgres?sslmode=disable SslMode:disable 
    DumpFile:server/migrations/dump.sql MigrationFolder:server/migrations 
    MigrationTable:schema_migrations SeedTables:[] ColumnType:integer Format:unix}
   
    PGMGR_URL='postgres://postgres@database:5432/postgres?sslmode=disable' pgmgr db migrate
    Error during migration: pq: role "root" does not exist

**Comment by rnubel** [comment]
Yeah, that's exactly it. My bad. Does https://github.com/rnubel/pgmgr/pull/36 make it work again?

**Comment by skinnyjames** [comment]
I think it will!  I'm not sure how to test it before you merge it though - It doesn't look like `go get` supports branches.

**Comment by rnubel** [comment]
Generally, I go directly into the source repository, clone the branch there and use `go build` to rebuild the binary. In this case, I'll just merge the fix, though.

**Comment by skinnyjames** [comment]
It works! Thanks!  I can close this issue, unless you prefer I not.

**Comment by rnubel** [comment]
Great, thanks for reporting this bug.
