### ISSUE TITLE
pgmgr db create when not local

### ISSUE THREAD

**Issue by yoda** [rnubel/pgmgr#38]
```
> pgmgr db create
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Error:  exit status 1
```

```
{
  "host": "192.168.56.2",
  "port": 5432,
  "username": "vagrant",
  "password": "vagrant",
  "database": "goscratch",
  "sslmode": "disable",
  "migration-table": "public.schema_migrations",
  "migration-folder": "migrations",
  "dump-file": "migrations/dump.sql",
  "column-type": "integer",
  "format": "unix"
}
```

When attempting  `pgmgr db create` it fails because the config is not passed into the createdb command correctly.

https://github.com/rnubel/pgmgr/blob/master/pgmgr/pgmgr.go#L48

passing in something manually, works and then the rest of the commands (migrate function correctly)
`createdb -h 192.168.56.2 -U vagrant -O vagrant goscratch`

```
> createbd -V
createdb (PostgreSQL) 9.6.3
```

**Comment by rnubel** [comment]
Thanks for the write-up, @yoda. You're right; none of the commands that execute shell directly (`create`, `drop`, `load`) are properly sending the host/port/user/password configuration. None of these commands are part of production usage, which is probably why it hasn't come up before.

Each of those config properties can be passed as arguments to the respective commands, except for password, which has to be sent as an environment variable. Should be pretty straightforward; I can work on a PR this week, unless someone else wants to contribute.

**Comment by rnubel** [comment]
This should be resolved now; pgmgr will dump its config to its local env before executing any of the PG binaries. There may be some issues with this in edge cases, so if anyone encounters a problem with this behavior, please open a new issue.
